// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/app/user/user.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/garoque/backend-code-challenge-snapfi/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockAppUserInterface is a mock of AppUserInterface interface.
type MockAppUserInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAppUserInterfaceMockRecorder
}

// MockAppUserInterfaceMockRecorder is the mock recorder for MockAppUserInterface.
type MockAppUserInterfaceMockRecorder struct {
	mock *MockAppUserInterface
}

// NewMockAppUserInterface creates a new mock instance.
func NewMockAppUserInterface(ctrl *gomock.Controller) *MockAppUserInterface {
	mock := &MockAppUserInterface{ctrl: ctrl}
	mock.recorder = &MockAppUserInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppUserInterface) EXPECT() *MockAppUserInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppUserInterface) Create(ctx context.Context, user entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAppUserInterfaceMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppUserInterface)(nil).Create), ctx, user)
}

// ReadAll mocks base method.
func (m *MockAppUserInterface) ReadAll(ctx context.Context) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadAll", ctx)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadAll indicates an expected call of ReadAll.
func (mr *MockAppUserInterfaceMockRecorder) ReadAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadAll", reflect.TypeOf((*MockAppUserInterface)(nil).ReadAll), ctx)
}

// ReadOneById mocks base method.
func (m *MockAppUserInterface) ReadOneById(ctx context.Context, userId string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadOneById", ctx, userId)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadOneById indicates an expected call of ReadOneById.
func (mr *MockAppUserInterfaceMockRecorder) ReadOneById(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadOneById", reflect.TypeOf((*MockAppUserInterface)(nil).ReadOneById), ctx, userId)
}
